CREATE TABLE `orders` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `fk_product_ids` varchar(45) NOT NULL,
  `fk_userid` int(11) DEFAULT NULL,
  `shipping_address_1` varchar(100) DEFAULT NULL,
  `shipping_address_2` varchar(100) DEFAULT NULL,
  `city` varchar(45) DEFAULT NULL,
  `state` varchar(45) DEFAULT NULL,
  `zip` varchar(45) DEFAULT NULL,
  `country` varchar(45) DEFAULT NULL,
  `phone` varchar(45) DEFAULT NULL,
  `order_date` datetime DEFAULT NULL,
  `expected_deleivery_date` datetime DEFAULT NULL,
  `card_number` varchar(45) DEFAULT NULL,
  `expiry_date` varchar(45) DEFAULT NULL,
  `CVV` varchar(45) DEFAULT NULL,
  `name_on_card` varchar(45) DEFAULT NULL,
  `order_amount` double DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
